<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmsTask.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.SmsTask</code>
 */
class SmsTask extends \Google\Protobuf\Internal\Message
{
    /**
     *模板编号
     *
     * Generated from protobuf field <code>string templateId = 1;</code>
     */
    private $templateId = '';
    /**
     *发送手机号码
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     */
    private $phone = '';
    /**
     *发送的短信内容,或者参数,每个参数以 | 隔开 如: "3502|注册操作"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     */
    private $content = '';
    /**
     *定时时间戳s,非定时任务此值传0
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\SmsTask::initOnce();
        parent::__construct();
    }

    /**
     *模板编号
     *
     * Generated from protobuf field <code>string templateId = 1;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->templateId;
    }

    /**
     *模板编号
     *
     * Generated from protobuf field <code>string templateId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->templateId = $var;

        return $this;
    }

    /**
     *发送手机号码
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *发送手机号码
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *发送的短信内容,或者参数,每个参数以 | 隔开 如: "3502|注册操作"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *发送的短信内容,或者参数,每个参数以 | 隔开 如: "3502|注册操作"
     *
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *定时时间戳s,非定时任务此值传0
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *定时时间戳s,非定时任务此值传0
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

