<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmsTask.proto

namespace GPBMetadata;

class SmsTask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a0d536d735461736b2e70726f746f120870726f746f636f6c22510a" .
            "07536d735461736b12120a0a74656d706c6174654964180120012809120d" .
            "0a0570686f6e65180220012809120f0a07636f6e74656e74180320012809" .
            "120c0a0474696d651804200128034a040805100b620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

