<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

namespace Message;

/**
 * Protobuf enum <code>Message\MsgPriority</code>
 */
class MsgPriority
{
    /**
     * Generated from protobuf enum <code>PRIORITY0 = 0;</code>
     */
    const PRIORITY0 = 0;
    /**
     * Generated from protobuf enum <code>PRIORITY1 = 1;</code>
     */
    const PRIORITY1 = 1;
    /**
     * Generated from protobuf enum <code>PRIORITY2 = 2;</code>
     */
    const PRIORITY2 = 2;
    /**
     * Generated from protobuf enum <code>PRIORITY3 = 3;</code>
     */
    const PRIORITY3 = 3;
    /**
     * Generated from protobuf enum <code>PRIORITY4 = 4;</code>
     */
    const PRIORITY4 = 4;
    /**
     * Generated from protobuf enum <code>PRIORITY5 = 5;</code>
     */
    const PRIORITY5 = 5;
    /**
     * Generated from protobuf enum <code>PRIORITY6 = 6;</code>
     */
    const PRIORITY6 = 6;
    /**
     * Generated from protobuf enum <code>PRIORITY7 = 7;</code>
     */
    const PRIORITY7 = 7;
    /**
     * Generated from protobuf enum <code>PRIORITY8 = 8;</code>
     */
    const PRIORITY8 = 8;
    /**
     * Generated from protobuf enum <code>PRIORITY9 = 9;</code>
     */
    const PRIORITY9 = 9;
}

